;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        forward-sexp
        ignore-preserving-kill-region
        indent-for-tab-command
        mouse-minor-mode-menu
        ))

(setq mc/cmds-to-run-once
      '(
        ignore
        keyboard-escape-quit
        lsp-ui-doc--handle-mouse-movement
        undo-redo
        ))
