;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        company-indent-or-complete-common
        forward-sexp
        ignore-preserving-kill-region
        indent-for-tab-command
        mouse-minor-mode-menu
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        dk/duplicate-line
        ignore
        keyboard-escape-quit
        lsp-ui-doc--handle-mouse-movement
        mouse-set-region
        undo-redo
        ))
